package mocks

import amqp "github.com/streadway/amqp"
import gateways "github.com/ghmeier/bloodlines/gateways"
import mock "github.com/stretchr/testify/mock"

// RabbitI is an autogenerated mock type for the RabbitI type
type RabbitI struct {
	mock.Mock
}

// Consume provides a mock function with given fields:
func (_m *RabbitI) Consume() (<-chan amqp.Delivery, error) {
	ret := _m.Called()

	var r0 <-chan amqp.Delivery
	if rf, ok := ret.Get(0).(func() <-chan amqp.Delivery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields:
func (_m *RabbitI) Destroy() {
	_m.Called()
}

// Produce provides a mock function with given fields: _a0
func (_m *RabbitI) Produce(_a0 interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ gateways.RabbitI = (*RabbitI)(nil)
