package mocks

import gateways "github.com/ghmeier/bloodlines/gateways"
import io "io"
import mock "github.com/stretchr/testify/mock"

// S3 is an autogenerated mock type for the S3 type
type S3 struct {
	mock.Mock
}

// Upload provides a mock function with given fields: bucket, name, body
func (_m *S3) Upload(bucket string, name string, body io.Reader) (string, error) {
	ret := _m.Called(bucket, name, body)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) string); ok {
		r0 = rf(bucket, name, body)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(bucket, name, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ gateways.S3 = (*S3)(nil)
