package mocks

import gateways "github.com/ghmeier/bloodlines/gateways"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/pborman/uuid"

// TownCenterI is an autogenerated mock type for the TownCenterI type
type TownCenterI struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: id
func (_m *TownCenterI) GetUser(id uuid.UUID) (string, error) {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ gateways.TownCenterI = (*TownCenterI)(nil)
