language: go
sudo: required
go:
  - tip
services:
  - docker
before_install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls
after_success:
	- docker build -t ghmeier/bloodlines .
	- docker push ghmeier/bloodlines
install:
  - godep restore
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  slack: mostlygifs:JqMktiWjFtPYI9H1NlupVuRk
