language: go

go:
  - 1.6

before_install:
  - go get github.com/tools/godep
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls

install:
  - godep restore

script:
  - goveralls -ignore=mocks/SQL.go -service=travis-ci
