language: go

go:
  - 1.6

before_install:
  - go get github.com/tools/godep
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls

install:
  - godep restore

script:
  - ./gosweep.sh
  - travis_retry goveralls -coverprofile=profile.cov -service=travis-ci
