language: go
sudo: required
go:
  - master
before_install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls
install:
  - godep restore
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  slack: mostlygifs:JqMktiWjFtPYI9H1NlupVuRk
