CREATE TABLE job(
	sendTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	sendStatus ENUM('READY', 'QUEUED', 'SUCCESS', 'FAILURE') NOT NULL,
	receipts VARCHAR(4096) NOT NULL
);