CREATE TABLE receipt(
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	sendState VARCHAR(20) NOT NULL,
	vals VARCHAR(4096) NOT NULL,
	contentId VARCHAR(36) NOT NULL, FOREIGN KEY fk_content(contentId) REFERENCES content(id),
	userId VARCHAR(36) NOT NULL
);